# Generated by Django 4.1.2 on 2022-12-18 06:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, unique=True, verbose_name='Mahsulot kategoriyasi')),
            ],
            options={
                'verbose_name': 'Kategoriya',
                'verbose_name_plural': 'Kategoriya',
            },
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Mahsulot nomi')),
                ('price', models.FloatField(default=0, verbose_name='Mahsulot narxi')),
                ('information', models.CharField(max_length=250, verbose_name='Mahsulot haqida informatsiya')),
                ('image', models.ImageField(upload_to='', verbose_name='Rasmi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name="Saytga qo'yilgan vaqti")),
                ('is_published', models.BooleanField(default=True, verbose_name='Saytga chiqazish')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category', to='store.category', verbose_name='Kategoriya')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Orders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='Soni')),
                ('status', models.BooleanField(default=False, verbose_name='Yetkazib berish')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Zakaz berilgan vaqti')),
                ('price', models.FloatField(default=0, verbose_name='Umumiy narxi')),
                ('user_telephone', models.CharField(max_length=20, verbose_name='Foydalanuvchi ismi')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='store.products', verbose_name='Mahsulot')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL, verbose_name='Zakaz bergan odam')),
            ],
            options={
                'verbose_name': 'Zakaz',
                'verbose_name_plural': 'Zakazlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
